spring:
  application:
    name: www
  datasource:
    url: jdbc:mysql://localhost:3306/www_tienda
    hikari:
      data-source-properties:
        sslMode: REQUIRED
        connectionTimeZone: UTC
    username: tienda_user
    password: $g4lNGnZRZHHuuLuaezxVTb0KH36uMJJLs8jpT74Ma
  jpa:
    hibernate:
      ddl-auto: validate
  server:
    servlet:
      encoding:
        charset: UTF-8
        force: true
jwt:
  secret: qUG9R8rvSw5Did2QpJgIQQXfNQdq91XqGYWRFC3LpNT
  expiration: 3600000